### ISSUE TITLE
Crash on incomplete metadata

### ISSUE THREAD

**Issue by indivisible** [rndusr/stig#41] opened 2017-11-13 21:32 UTC
https://github.com/rndusr/stig/blob/e4ae55ee0e60833ce7199944855aa0b6a1afbcf1/stig/client/aiotransmission/torrent.py#L324

stig 0.7.3a crashes after a few seconds when I have a magnet transfer whose metadata is not yet loaded. Since totalSize is 0 it will cause a division by zero error.

Backtrace:
```
Traceback (most recent call last):
  File "/home/user/.local/bin/stig", line 11, in <module>
    sys.exit(run())
  File "/home/user/.local/lib/python3.5/site-packages/stig/__init__.py", line 17, in run
    main.run()
  File "/home/user/.local/lib/python3.5/site-packages/stig/main.py", line 119, in run
    if not tui.run(run_commands):
  File "/home/user/.local/lib/python3.5/site-packages/stig/tui/main.py", line 212, in run
    urwidloop.run()
  File "/home/user/.local/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/user/.local/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/user/.local/lib/python3.5/site-packages/stig/tui/urwidpatches.py", line 56, in run
    raise self._exc_info
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/user/.local/lib/python3.5/site-packages/urwid/main_loop.py", line 1289, in faux_idle_callback
    callback()
  File "/home/user/.local/lib/python3.5/site-packages/urwid/main_loop.py", line 564, in entering_idle
    self.draw_screen()
  File "/home/user/.local/lib/python3.5/site-packages/urwid/main_loop.py", line 578, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/home/user/.local/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/user/.local/lib/python3.5/site-packages/urwid/widget.py", line 1750, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/home/user/.local/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/user/.local/lib/python3.5/site-packages/urwid/container.py", line 1526, in render
    canv = w.render((maxcol, rows), focus=focus and item_focus)
  File "/home/user/.local/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/user/.local/lib/python3.5/site-packages/stig/tui/tabs.py", line 129, in render
    canvas = current_widget.render(size_content, focus)
  File "/home/user/.local/lib/python3.5/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/user/.local/lib/python3.5/site-packages/stig/tui/torrent/tlist.py", line 116, in render
    self._update_listitems()
  File "/home/user/.local/lib/python3.5/site-packages/stig/tui/torrent/tlist.py", line 131, in _update_listitems
    tw.update(tdict[tid])
  File "/home/user/.local/lib/python3.5/site-packages/stig/tui/torrent/tlist.py", line 41, in update
    widget.update(torrent)
  File "/home/user/.local/lib/python3.5/site-packages/stig/tui/torrent/__init__.py", line 88, in update
    self.data.update(data)
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/aiotransmission/torrent.py", line 388, in __getitem__
    value = _MODIFY[key](raw)
  File "/home/user/.local/lib/python3.5/site-packages/stig/client/aiotransmission/torrent.py", line 324, in <lambda>
    '%uploaded'         : lambda raw: raw['uploadedEver'] / raw['totalSize'] * 100,
ZeroDivisionError: division by zero
```

**Comment by rndusr** [comment] 2017-11-13 21:54
Duplicate of #29

You can install from the dev branch for a fix.
Or wait. I'm planning to make a new release soon.

**Comment by rndusr** [comment] 2017-11-25 16:32
This is now fixed in the latest release.

**Closed by rndusr** 2017-11-25 16:32 UTC
