### ISSUE TITLE
rate limit for download goes up only

### ISSUE THREAD

**Issue by oblitum** [rndusr/stig#44] opened 2017-11-29 16:15 UTC
Both shift down and shift up is making the rate limit to just increase. Uploading rate limit with left and right is OK.

**Comment by rndusr** [comment] 2017-11-29 16:24
Can't reproduce.

Does the issue persist if you run `stig -C`?

Can you post the output of `stig help keys | grep shift-down`?

**Comment by oblitum** [comment] 2017-11-29 16:28
> Does the issue persist if you run `stig -C`?

Yes

> Can you post the output of `stig help keys | grep shift-down`?

```
~ ❯❯❯ stig help keys | grep shift-down
  <shift-down>   set srv.limit.rate.down -=100kB
```

**Comment by oblitum** [comment] 2017-11-29 16:29
What's a command so I can set it back to unlimited?

**Comment by rndusr** [comment] 2017-11-29 16:33
Did this work previously and change with the recent release?

> ```
> ~ ❯❯❯ stig help keys | grep shift-down
>   <shift-down>   set srv.limit.rate.down -=100kB
> ```

What happens if you run `stig set srv.limit.rate.down -=100kB` manually?

**Comment by oblitum** [comment] 2017-11-29 16:37
> Did this work previously and change with the recent release?

It's is the first time I'm using these hotkeys and trying to change rate limits, solely upload rate is behaving as expected.

> What happens if you run `stig set srv.limit.rate.down -=100kB` manually?

It decreases as expected.

**Comment by oblitum** [comment] 2017-11-29 16:38
What's the command to reset it back to unlimited?

**Comment by rndusr** [comment] 2017-11-29 16:45
> What's a command so I can set it back to unlimited?

`stig srv.limit.rate.down off` should work.

I think it might have something to do with your terminal emulator.

Can you bind any other commands to shift-up? Run `stig bind shift-up quit` and
see if pressing shift-up quits.

Or try a different terminal emulator.

**Comment by oblitum** [comment] 2017-11-29 17:19
`stig srv.limit.rate.down off` worked.

Well, my arrow keys work well in my terminal emulators, but I just got things messed try to make shift arrow work with anything. I tried on linux tty and then noticed that it simply doesn't accept shift, I also tried Cool Retro Term which I had installed already and it was worse.

My suggestion would be of defining better keybings that would at least support bare linux terminal without problems.

I didn't bind it to quit because I don't know how to reset it back later.

**Comment by oblitum** [comment] 2017-11-29 17:20
Specially if the keybings are  vi-like :)

**Comment by rndusr** [comment] 2017-11-29 17:33
> I tried on linux tty and then noticed that it simply doesn't accept shift

Confirmed.

> My suggestion would be of defining better keybings that would at least support bare linux terminal without problems.

You mean the console? I don't think many people use that, and if they do,
changing the keybindings is easy enough. Which is what I suggest for your
case. Shift-up works in all the terminals I've tried (urxvt, sakura, termit and
xterm).

```
echo 'bind <the-key-you-want> set srv.limit.rate.down -=100kB' >> ~/.config/stig/rc
```

> I didn't bind it to quit because I don't know how to reset it back later.

All bindings are only active for the session. And you can unbind them in the
session with the `unbind` command.

**Comment by oblitum** [comment] 2017-11-29 17:35
My terminal is termite (it's vte base, quite popular). I also use tmux.

**Comment by oblitum** [comment] 2017-11-29 17:37
Also, yes I meant the console. I wished stig to work fine on a tty window...

**Comment by oblitum** [comment] 2017-11-29 17:40
I've `stig bind shift-up quit` and it indeed quit on shift-up, I've then `stig bind shift-down quit` and it didn't quit, just kept increasing the rate instead.

**Comment by rndusr** [comment] 2017-11-29 18:18
I use termit, which is also vte-based. Although termite uses a forked vte if I'm
not mistaken.

Everything works fine for me with tmux, so it looks like it has something to do
with termite. Unfortunately, I can't confirm that as termite is not available on
my distro. Maybe someone else can help and see if shift-up works with termite?

**Comment by kutsan** [comment] 2018-01-21 11:45
@oblitum Could you please execute `sed --silent l` and press <kbd>Shift + UpArrow</kbd>, enter and <kbd>Shift + DownArrow</kbd>, enter, then send the output?

**Comment by RobertSacks** [comment] 2018-04-05 00:15
I had this same issue only when using st with tmux. This is a bug with tmux (see this [issue](https://github.com/tmux/tmux/issues/1105)). Adding `set -as terminal-overrides ',st*:kind@:kri@'` to your .tmux.conf should fix the issue.

**Comment by rndusr** [comment] 2018-08-29 17:54
I'm closing this because @oblitum doesn't seem to care about this anymore and
it's easy enough to change the default keybindings.

But feel free to convince me otherwise.

**Closed by rndusr** 2018-08-29 17:55 UTC
Labels: help wanted
