### ISSUE TITLE
Add queue visualization and re-ordering

### ISSUE THREAD

**Issue by Soundtoxin** [rndusr/stig#180] opened 2020-10-03 21:48 UTC
(feature request)
Show where something is in the queue with a number, and give the option to change the order of the queue.

Hopefully I'm not overlooking an existing feature. There's no help topic (`stig -h`) for queue, and no commands show up if I type `:queue`.

I used to tweak the queue a lot in Deluge. Use-case is something like having way more torrents added than you can download at once, and then deciding after adding them which ones you care about the most, and raising them in the queue so they finish first.

**Comment by rndusr** [comment] 2020-10-04 08:44
Duplicate of #40.

**Closed by rndusr** 2020-10-04 08:44 UTC
