### ISSUE TITLE
[Feature Request] Add support for alt-speed (AKA turtle mode)

### ISSUE THREAD

**Issue by SeerLite** [rndusr/stig#176] opened 2020-08-31 07:25 UTC
https://github.com/transmission/transmission/wiki/Editing-Configuration-Files#bandwidth (didn't find any other official info about it on my quick search)

Currently, there's no way to toggle or turn on/off the turtle mode from within stig. Turning it on externally won't show any indication in the UI either.

And as always thank you for the amazing client :)

**Comment by rndusr** [comment] 2020-08-31 08:32
You're welcome. (:

This is a duplicate of #106, in which I've explained a workaround.

**Closed by rndusr** 2020-08-31 08:32 UTC

**Comment by SeerLite** [comment] 2020-08-31 20:36
Ah, sorry about that! I somehow didn't see that one when searching
