### ISSUE TITLE
set tab title

### ISSUE THREAD

**Issue by daulpavis** [rndusr/stig#22] opened 2017-04-21 03:54 UTC
Enhancement suggestion: The ability to control the title text of each tab created. 

This would be for the sake of giving a short, easily readable name to long and complex filters, or reducing the horizontal space taken up for multiple tabs.

**Comment by rndusr** [comment] 2017-04-21 10:12
Duplicate of #17

It's implemented in the `dev` branch.

**Closed** 2017-04-22 01:09 UTC
