### ISSUE TITLE
Can't log in without username

### ISSUE THREAD

**Issue by cerinthus** [rndusr/stig#147] opened 2020-05-09 14:54 UTC
If transmission is configured to use a password but no username, stig fails as unauthorized.

**Comment by rndusr** [comment] 2020-05-09 17:23
Can you tell me how to reproduce this issue? This is working for me.

    $ transmission-daemon --config-dir /tmp/transmission.tmp
      --download-dir /tmp/transmission.tmp --log-debug --foreground \
      --no-dht --port 1234 --peerport 4321 --auth --password bar
    [lots of output]

In another terminal:

    $ stig --norcfile set connect.host localhost and set connect.port 1234 \
      and set connect.password bar and set | grep '^srv.path'
    srv.path.complete       /tmp/transmission.tmp   disconnected    Where to put downloaded files
    srv.path.incomplete     disabled        disconnected    Where to put partially downloaded files

**Comment by cerinthus** [comment] 2020-05-14 11:20
Sorry, I didn't realize it only happned with SSL enabled or I'd have specified.

**Comment by rndusr** [comment] 2020-05-18 16:41
How do I set up an SSL reverse proxy?

I've managed to set up nginx with SSL and forward connections to Transmission. It works in
the browser if I tell it to ignore the warning. I can access Transmission's web interface.

But with stig I get this exception:

```
ClientConnectorSSLError(ConnectionKey(
    host='localhost', port=1234, is_ssl=True, ssl=None,
    proxy=None, proxy_auth=None, proxy_headers_hash=None),
    SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)'))
```

It seems like the server and stig use different SSL versions, but I've told nginx to
accept any version number. At least I think that's what this line does?

```
ssl_protocols       SSLv2 SSLv3 TLSv1 TLSv1.1 TLSv1.2;
```

**Comment by rndusr** [comment] 2020-05-18 17:04
OK, scratch all that, I mixed up the ports.

**Comment by rndusr** [comment] 2020-05-18 17:24
Now I'm getting this:

```
SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)'))
```

I've tried adding the certificate (.key + .crt) to /etc/ssl/certs, but no dice.

**Comment by rndusr** [comment] 2020-07-04 10:29
Closing because OP is not responding.

**Closed by rndusr** 2020-07-04 10:29 UTC
