### ISSUE TITLE
Moving files

### ISSUE THREAD

**Issue by bograt** [rndusr/stig#165] opened 2020-06-03 06:04 UTC
Moving files isn't working. I don't think it's a permissions error either, as I've chmod -R 755'd the default directory /var/lib/transmission/Downloads
It seems like everything is working normally, but the files don't get moved.
Edit: I'm stupid, the location changes after restarting the daemon.

**Comment by bograt** [comment] 2020-06-03 06:09
Okay, no nevermind I'm still having the problem. It also will not let me unpause the torrents that were successfully moved into my home directory.

**Comment by rndusr** [comment] 2020-06-03 07:34
First of all, if this is a bug with stig, I need to be able to reproduce your problem.
You need to tell me exactly what you did in such a way that I can do the same thing and
experience the same issue.

Also, check the output of Transmission. Depending on your distro and setup, this might be
in /var/log/syslog or the systemd log. You might have to increase the verbosity level,
e.g. --log-debug.

**Comment by rndusr** [comment] 2020-07-04 10:28
Closing because OP is not responding.

**Closed by rndusr** 2020-07-04 10:28 UTC
